import { Inter } from 'next/font/google'
import Head from 'next/head'

import _app from '@/pages/_app'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Travel</title>
        <meta content="Generated by create next app" name="description" />
        <meta content="width=device-width, initial-scale=1" name="viewport" />
        <link href="/favicon.ico" rel="icon" />
      </Head>
      <main>
        <_app></_app>
        <div></div>
      </main>
    </>
  )
}
